#указываем версию файла docker-compose
version: '3.8'

#начало определения контейнеров
services:
#указываем имя сервиса (в моем случае app)
  app:
  #указываем, что образ собран из Dockerfile и прописываем путь к docker-compose.yml 
    build:
      context: .
      dockerfile: Dockerfile
    #задаем имя контейнеру
    container_name: task_nine
    #указываем, что порт на локалхосте связан с портом 1301 в контейнере
    ports:
      - "127.0.0.1:1301:1301"
    #тут устанавливаются переменные окружения: в нашем случае Flask в режим разработки
    environment:
      - FLASK_ENV=development
    #указываем, что текущую директорию монтируем в папку /app в контейнере
    volumes:
      - .:/app
    #контейнер будет перезапущен, если не остановлен вручную
    restart: unless-stopped
    # Настройка проверки параметров(работы) контейнера
    healthcheck:
    #тестируем на localhost:1301
      test: ["CMD", "curl", "-f", "http://localhost:1301"]
    #интервал 30 сек
      interval: 30s
    #ждем ответа 10 сек
      timeout: 10s
    #кол-во попыток перед тем как будем считать контейнер нефункциональным 
      retries: 3
      